### ISSUE TITLE
Can't run it (Linux).

### ISSUE THREAD

**Issue by Achaean** [davidjoffe/dave_gnukem#114]
Compilation completed without errors, but trying to run it, results in a flashing and autoclosing window.
No error messages.

In full-screen mode only, also fails to restore my desktop resolution (which has to be manually).
Tested at Debian Jessie (oldstable) x64 KDE.

**Comment by pocak100** [comment]
Make sure you have cloned the data files from https://github.com/davidjoffe/gnukem_data into a folder called `data`.

If that doesn't help, please post the contents of `~/.gnukem/logs/DaveGnukem.log`.

@davidjoffe, it would be a good idea to write error messages to the terminal as well.

**Comment by Achaean** [comment]
Indeed! That solved the problem.
**THANKS!!!** :-)

**Comment by davidjoffe** [comment]
I've also just pushed a small change that checks for presence of data folder on run, and just printf's a small message like 'data folder not found' and a little bit of guidance to help point the user in the right direction, hope that might also help for situations like this in future, instead of the dramatic insta-exit with zero clue.
